[workspace]
resolver = "2"
members = [
    "crates/zavora-docx-opc",
    "crates/zavora-docx-oxml",
    "crates/zavora-docx",
    "crates/zavora-docx-layout",
    "crates/zavora-docx-pdf",
    "crates/zavora-docx-html",
    "crates/zavora-docx-cli",
]
exclude = [
    "crates/zavora-docx-wasm",
]

[workspace.package]
version = "0.1.4"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.94.1"
authors = ["Atul Sharma"]
repository = "https://github.com/zavora-ai/zavora-docx"
homepage = "https://zavora.ai"
keywords = ["docx", "word", "pdf", "ooxml", "document"]
categories = ["parser-implementations", "text-processing"]

[workspace.dependencies]
# Internal crates
zavora-docx-opc = { path = "crates/zavora-docx-opc", version = "0.1.4" }
zavora-docx-oxml = { path = "crates/zavora-docx-oxml", version = "0.1.4" }
zavora-docx = { path = "crates/zavora-docx", version = "0.1.4" }
zavora-docx-layout = { path = "crates/zavora-docx-layout", version = "0.1.4" }
zavora-docx-pdf = { path = "crates/zavora-docx-pdf", version = "0.1.4" }
zavora-docx-html = { path = "crates/zavora-docx-html", version = "0.1.4" }

# External dependencies
zip = "8.1"
quick-xml = "0.41"
thiserror = "2"
fontdb = "0.23"
rustybuzz = "0.20"
ttf-parser = "0.25"
unicode-linebreak = "0.1"
itoa = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
