[package]
name = "zavora-docx"
description = "High-level API for reading, writing, and converting DOCX documents"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"

[dependencies]
zavora-docx-opc = { workspace = true }
zavora-docx-oxml = { workspace = true }
zavora-docx-layout = { workspace = true }
zavora-docx-pdf = { workspace = true }
zavora-docx-html = { workspace = true }
thiserror = { workspace = true }
regex = "1"
serde_json = { workspace = true }

[dev-dependencies]
zip = { workspace = true }
